name: Train and Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup GCP client
      uses: google-github-actions/setup-gcloud@main
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pip install requests
        pip install pytest-cov
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: junit/test-results.xml
    
    - name: Download the latest dataset
      run: |
        gsutil cp gs://dataset_practicaml/default.csv datasets/default.csv

    - name: Run training task
      run: |
        python steps/train.py --path=datasets/default.csv

    - name: Upload new model and associated metrics
      run: |
        gsutil cp artifacts/pipeline.joblib gs://practicaml-cicd-363402.appspot.com/ml-heart-disease/models/latest.joblib
        gsutil cp artifacts/pipeline.joblib gs://practicaml-cicd-363402.appspot.com/ml-heart-disease/models/${{ env.GITHUB_RUN_ID }}.joblib
        gsutil cp artifacts/metrics.json gs://practicaml-cicd-363402.appspot.com/ml-heart-disease/models/metrics/${{ env.GITHUB_RUN_ID }}.joblib


    - name: Deploy model as Cloud Function
      run: | 
        gcloud functions deploy heart-disease --entry-point=predict_handler --runtime=python37 --project=${{ secrets.GCP_PROJECT_ID }} --allow-unauthenticated --trigger-http